[env:cyd]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_unflags =
    -std=gnu++11
build_flags =
    -std=gnu++17
    -Wall
board_build.partitions = huge_app.csv
lib_deps =
    lovyan03/LovyanGFX
    tzapu/WiFiManager
    mathieucarbou/ESP Async WebServer
    mathieucarbou/AsyncTCP
    bblanchon/ArduinoJson
